#****************************************************************************
#                                                                           *
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY     *
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE       *
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR     *
# PURPOSE.                                                                  *
#                                                                           *
# Copyright (C) 1993-95  Microsoft Corporation.  All Rights Reserved.       *
#                                                                           *
#****************************************************************************

# sample make file for building vfintd virtual device for Windows

NAME = VFINTD

#       Definitions for the debug level 

!ifdef DEBUG
DDEBUG  =-DDEBLEVEL=1 -DDEBUG
!else
DDEBUG  =-DDEBLEVEL=0
!endif

#       Definitions for MASM 6 Assembler

ASM    = ml
AFLAGS = -coff -DBLD_COFF -DIS_32 -W2 -c -Cx -Zm -DMASM6 $(DDEBUG)
ASMENV = ML
LFLAGS = /VXD /NOD

#       MASM 6 only inference rules

.asm.obj:
    set $(ASMENV)=$(AFLAGS)
	$(ASM) -Fo$*.obj $<
	set $(ASMENV)=

!ifdef MASTER_MAKE
all : $(NAME).vxd tstfint.exe
!else
all : $(NAME).vxd
!endif

#
# to build tstfint.exe run ddkenv 16 and run nmake tstfint.exe
#
!ifdef MASTER_MAKE
tstfint.exe: SET_BUILD_BITS_16 tstfint.obj
!else
tstfint.exe: tstfint.obj
!endif
      link tstfint.obj;     

tstfint.obj:  tstfint.asm vfintd.inc
        ml -W2 -c -Cx -Zm -DMASM6 $(DDEBUG) tstfint.asm

vfintd.obj : vfintd.asm

OBJS =  vfintd.obj 

!ifdef MASTER_MAKE
$(NAME).vxd: SET_BUILD_BITS_32 $(NAME).def $(OBJS)
!else
$(NAME).vxd: $(NAME).def $(OBJS)
!endif
        link @<<$(NAME).lnk
$(LFLAGS) 
/OUT:$(NAME).vxd
/MAP:$(NAME).map
/DEF:$(NAME).def
$(OBJS)
<<
        mapsym -s -o $(NAME).sym $(NAME).map

!ifdef MASTER_MAKE
BUILD_TYPE=base
!INCLUDE $(DDKROOT)\master.mk
!endif

clean:
	-@del *.obj
	-@del *.vxd
	-@del *.exp
	-@del *.lib
	-@del *.map
	-@del *.sym
	-@del *.exe
